#ifndef SOLENOID_KEYCODES_H
#define SOLENOID_KEYCODES_H
#include "quantum_keycodes.h"

#define OLD_SAFE_RANGE SAFE_RANGE
#undef SAFE_RANGE

enum user_solenoid {
  SOLENOID_TOGGLE = OLD_SAFE_RANGE,
  SOLENOID_INVERT,
  SOLENOID_DWELL_MINUS,
  SOLENOID_DWELL_PLUS,
  SOLENOID_PROFILE_0,
  SOLENOID_PROFILE_1,
  SOLENOID_PROFILE_2,
  SAFE_RAGE,
};

#define KC_STOG SOLENOID_TOGGLE
#define KC_SOIN SOLENOID_INVERT
#define KC_SDM  SOLENOID_DWELL_MINUS
#define KC_SDP  SOLENOID_DWELL_PLUS
#define KC_SOP0 SOLENOID_PROFILE_0
#define KC_SOP1 SOLENOID_PROFILE_1
#define KC_SOP2 SOLENOID_PROFILE_2

#endif
